services:
  backend:
    build:
      context: ../backend
    container_name: backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ../frontend
    container_name: frontend

    ports:
      - "8080:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:8081


  postgres:
    image: postgres:11
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: registration_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: