services:
  backend:
    build:
      context: ../backend
    container_name: backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ../frontend
    container_name: frontend

    ports:
      - "8080:8080"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000


  mariadb:
    image: mariadb:10.5
    restart: always
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: registration_db
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: